--기본 SELECT
SELECT EMPNO, ENAME, SAL, JOB FROM EMP;

--산술표현식
SELECT ENAME, SAL, SAL+300 FROM EMP;
SELECT ENAME, SAL, 2*SAL+100 FROM EMP;
SELECT ENAME, SAL, 2*(SAL+100) FROM EMP;

--NULL값
SELECT EMPNO, ENAME, SAL, COMM, COMM+300 FROM EMP;

--컬럼 별칭
SELECT ENAME AS NAME, SAL, SAL*12 AS "Annual Salary" FROM EMP;

--LITERAL 문자열
SELECT ENAME 결과1, 'Abc' 결과2, SAL 결과3, 500 결과4 FROM EMP;

--연결(Concatenation) 연산자
SELECT ENAME||':'||EMPNO||':'||JOB "전체정보" FROM EMP;
SELECT ENAME||' IS A ' || JOB "EMPLOYEES DETAILS" FROM EMP;
SELECT ENAME||' : 1 YEAR SALARY = ' || SAL "MONTHLY" FROM EMP;

--중복 행 제거(DISTINCT) -> SELECT뒤에 나와야한다.
SELECT DISTINCT JOB FROM EMP;
SELECT DISTINCT DEPTNO, JOB FROM EMP;

--PSEUDO COLUMN(의사 열)
--ROWNUM : 각 행에 임시로 부여되는 일련 변호
--ROWID : 테이블 내 특정 행을 유일하게 구별해주는 값
SELECT ROWID, ROWNUM, ENAME, SAL FROM EMP;

--행의 제한

--WHERE절
--비교연산자
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE JOB='MANAGER';
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE SAL >= 3000;
SELECT ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO<>30;

--비교연산자
SELECT ENAME, JOB, SAL, DEPTNO FROM EMP WHERE SAL BETWEEN 1300 AND 1700;
SELECT ENAME, JOB, SAL, DELTNO FROM EMP WHERE SAL BETWEEN 1700 AND 1300;    --에러 발생
SELECT EMPNO, ENAME, JOB, SAL, HIREDATE FROM EMP WHERE EMPNO IN(7902, 7788, 7566);
SELECT ENAME, SAL, JOB FROM EMP WHERE ENAME LIKE '_A%';
SELECT ENAME, SAL, JOB FROM EMP WHERE ENAME LIKE '%A%';
SELECT ENAME, SAL, JOB FROM EMP WHERE ENAME LIKE '%#%%';
SELECT * FROM EMP WHERE COMM IS NULL;   --NULL은 어떻게 계산해도 NULL이 나온다.

--논리 연산자
SELECT EMPNO, ENAME, JOB, SAL, HIREDATE, DEPTNO FROM EMP WHERE SAL>=2800 AND JOB='MANAGER';
SELECT EMPNO, ENAME, JOB, SAL, HIREDATE, DEPTNO FROM EMP WHERE SAL>=2800 OR JOB='MANAGER';

--NOT 연산자
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE JOB NOT IN('MANAGER', 'CLERK', 'ANALYST');
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE SAL NOT BETWEEN 1000 AND 3000;
SELECT * FROM EMP WHERE ENAME NOT LIKE 'A%';
SELECT ENAME, SAL, COMM, DEPTNO FROM EMP WHERE COMM IS NOT NULL;

--연산자 우선순위
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE SAL > 1500 AND JOB = 'PRESIDENT' OR JOB = 'SALESMAN';
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE SAL > 1500 AND (JOB = 'PRESIDENT' OR JOB = 'SALESMAN');
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE SAL> 1500 AND JOB IN('PRESIDENT', 'SALESMAN');

--데이터 정렬
SELECT EMPNO, ENAME, JOB, SAL, HIREDATE, DEPTNO FROM EMP ORDER BY HIREDATE;
SELECT EMPNO, ENAME, JOB, DEPTNO, SAL FROM EMP ORDER BY DEPTNO, SAL DESC;
SELECT EMPNO, ENAME, JOB, DEPTNO, SAL FROM EMP ORDER BY 4, 5 DESC;
SELECT ENAME, SAL, SAL * 12 "ANN_SAL" FROM EMP ORDER BY ANN_SAL;
SELECT DISTINCT DEPTNO, JOB FROM EMP ORDER BY JOB;
--SELECT DISTINCT JOB, SAL+COMM FROM EMP ORDER BY SAL;
SELECT DISTINCT JOB, SAL+COMM FROM EMP ORDER BY 2; --NULL계산은 무조건 NULL

--단일행 함수
--문자 함수(1)
SELECT EMPNO, ENAME, JOB, LOWER(JOB), INITCAP(JOB) FROM EMP WHERE DEPTNO = 10;
SELECT EMPNO, ENAME, JOB, CONCAT(EMPNO, ENAME) ENAME1, CONCAT(ENAME, EMPNO) E_EMPNO, CONCAT(ENAME, JOB) E_JOB FROM EMP WHERE DEPTNO = 10;
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE SUBSTR(ENAME, 1, 1) > 'K' AND SUBSTR(ENAME, 1, 1) < 'Y' ORDER BY ENAME;
SELECT EMPNO, ENAME, LENGTH(ENAME), SAL, LENGTH(SAL) FROM EMP WHERE DEPTNO=20;
SELECT ENAME, INSTR(ENAME, 'L') E_NULL, INSTR(ENAME, 'L', 1, 1) E_11, INSTR(ENAME, 'L', 1, 2) E_12, INSTR(ENAME, 'L',  4, 1) E_41 FROM EMP ORDER BY ENAME;
SELECT SUBSTRB('I AM HERE WITH YOU', 5, 3) 결과1, SUBSTR('나 여기 있어', 5, 3) 결과2, SUBSTRB('나 여기 있어', 5, 3) 결과3 FROM DUAL; 
SELECT ENAME, SUBSTR(ENAME, 1, 3), SUBSTR(ENAME, 3), SUBSTR(ENAME, -3, 2) FROM EMP WHERE DEPTNO = 10;

--문자 함수(2)
SELECT ENAME, LPAD(ENAME, 15, '*'), SAL, LPAD(SAL, 10, '*') FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, RPAD(ENAME, 15, '*'), SAL, RPAD(SAL, 10, '*') FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, JOB, LTRIM(JOB, 'A'), SAL, LTRIM(SAL, 1) FROM EMP WHERE DEPTNO = 20;
SELECT ENAME, JOB, RTRIM(JOB, 'T'), SAL, RTRIM(SAL, 0) FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, REPLACE(ENAME, 'SC', '*?') FROM EMP WHERE DEPTNO = 20;
SELECT ENAME, TRANSLATE(ENAME, 'SC', '*?') FROM EMP WHERE DEPTNO = 20;
SELECT TRIM(LEADING 'A' FROM 'AABDCADD'),TRIM('A' FROM 'AABDCADD'),TRIM(TRAILING 'D' FROM 'AABDCADD') FROM DUAL;
SELECT EMPNO, ENAME, TRANSLATE(ENAME, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')  FROM EMP WHERE DEPTNO = 10;

--숫자 함수
SELECT ROUND(4567.789) 결과1, ROUND(4567.678, 0) 결과2, ROUND(4567.678, 2) 결과3, ROUND(4567.678, -2) FROM DUAL;
SELECT TRUNC(4567.789) 결과1, TRUNC(4567.678, 0) 결과2, TRUNC(4567.678, 2) 결과3, TRUNC(4567.678, -2) FROM DUAL;
SELECT POWER(2, 10) 결과2, CEIL(3.7)결과2, FLOOR(3.7) 결과3 FROM DUAL;
SELECT SAL, MOD(SAL, 30) FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, SAL, SIGN (SAL-2975) FROM EMP WHERE DEPTNO  = 20;

--날짜 계산 결과
SELECT ENAME, HIREDATE, HIREDATE+3, HIREDATE+5/24 FROM EMP WHERE DEPTNO = 30;
SELECT ENAME, HIREDATE, SYSDATE, SYSDATE-HIREDATE "TOTAL DAY", TRUNC((SYSDATE-HIREDATE)/7, 0) WEEKS, ROUND(MOD((SYSDATE-HIREDATE), 7), 0) DAYS FROM EMP ORDER BY "TOTAL DAY" DESC;
SELECT EXTRACT (DAY FROM SYSDATE) 일자, EXTRACT(MONTH FROM SYSDATE) 월, EXTRACT(YEAR FROM SYSDATE) 연도 FROM DUAL;
SELECT SYSTIMESTAMP A, EXTRACT(HOUR FROM SYSTIMESTAMP) B, TO_CHAR(SYSTIMESTAMP, 'HH24') C FROM DUAL;
SELECT SYSTIMESTAMP, TO_CHAR(SYSTIMESTAMP, 'HH24') CH, EXTRACT(TIMEZONE_HOUR FROM SYSTIMESTAMP) ETZH, EXTRACT (HOUR FROM SYSTIMESTAMP) EH, EXTRACT(HOUR FROM CAST(SYSTIMESTAMP AS TIMESTAMP)) EHC FROM DUAL;
SELECT SYSTIMESTAMP, EXTRACT(HOUR FROM SYSTIMESTAMP) H1, EXTRACT(HOUR FROM SYSTIMESTAMP) + EXTRACT(TIMEZONE_HOUR FROM SYSTIMESTAMP) H2 FROM DUAL;
SELECT ENAME, HIREDATE, EXTRACT(DAY FROM HIREDATE) "DAY", EXTRACT(YEAR FROM HIREDATE) "YEAR", EXTRACT(MONTH FROM HIREDATE) "MONTH" FROM EMP WHERE DEPTNO = 20;

--날짜 함수
SELECT ENAME, HIREDATE, SYSDATE, MONTHS_BETWEEN(SYSDATE, HIREDATE) M_BETWEEN, TRUNC(MONTH_BETWEEN(SYSDATE, HIREDATE), 0)T_BETWEEN FROM EMP WHERE DEPTNO = 10 ORDER BY MONTHS_BETWEEN(SYSDATE, HIREDATE) DESC;
SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 5) A_MONTH FROM EMP WHERE DEPTNO IN(10, 30) ORDER BY HIREDATE DESC;
SELECT ENAME, HIREDATE, NEXT_DAY(HIREDATE, 6) FRIDAY, NEXT_DAY(HIREDATE, 7) SATURDAY FROM EMP WHERE DEPTNO=10 ORDER BY HIREDATE DESC;
SELECT EMPNO, ENAME, HIREDATE, LAST_DAY(HIREDATE) LASTD, LAST_DAY(HIREDATE) -HIREDATE FROM EMP ORDER BY LAST_DAY(HIREDATE) - HIREDATE DESC;